#!/bin/bash

#PBS -l select=1:ncpus=32:ngpus=1:mem=128GB
#PBS -l walltime=1:00:00
#PBS -N create_fake_full_scale
#PBS -o create_fake_full_scale_output.log
#PBS -e create_fake_full_scale_error.log

cd $PBS_O_WORKDIR

module purge
module load CUDA/11.7.0
module load cuDNN/8.4.1.50-CUDA-11.7.0

source /scratch/e1456870/ee4115/venv/bin/activate

python3 -u create_fake_full_scale.py > create_fake_full_scale.log 2>&1
